// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcvK6M9PsebnTJTEae5UZMSafS_Y9hXc',
    appId: '1:626177959136:web:62b9d5a2fbc241350b1c85',
    messagingSenderId: '626177959136',
    projectId: 'foda-application',
    authDomain: 'foda-application.firebaseapp.com',
    storageBucket: 'foda-application.appspot.com',
    measurementId: 'G-FHXZ7EF4D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAneDSbsyXfFeXmdsE6jSRVhetzju_5deU',
    appId: '1:626177959136:android:db2e4dee6f9153800b1c85',
    messagingSenderId: '626177959136',
    projectId: 'foda-application',
    storageBucket: 'foda-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYgqWwoSwDrSk3URhXSl7_zweNeVdJ250',
    appId: '1:626177959136:ios:a260cd1e252cdb910b1c85',
    messagingSenderId: '626177959136',
    projectId: 'foda-application',
    storageBucket: 'foda-application.appspot.com',
    iosClientId: '626177959136-569hi7r3j58m3lapd81nsav1f25engjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.foda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYgqWwoSwDrSk3URhXSl7_zweNeVdJ250',
    appId: '1:626177959136:ios:b80c28dc844e53510b1c85',
    messagingSenderId: '626177959136',
    projectId: 'foda-application',
    storageBucket: 'foda-application.appspot.com',
    iosClientId: '626177959136-8sk6bf3godgh3g4sok84lbjfl82cms2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.foda.RunnerTests',
  );
}
